// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.0
// source: live/sites/v1alpha1/database.proto

package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BackupState int32

const (
	BackupState_CREATED  BackupState = 0
	BackupState_FINISHED BackupState = 1
	BackupState_DELETED  BackupState = 2
)

// Enum value maps for BackupState.
var (
	BackupState_name = map[int32]string{
		0: "CREATED",
		1: "FINISHED",
		2: "DELETED",
	}
	BackupState_value = map[string]int32{
		"CREATED":  0,
		"FINISHED": 1,
		"DELETED":  2,
	}
)

func (x BackupState) Enum() *BackupState {
	p := new(BackupState)
	*p = x
	return p
}

func (x BackupState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackupState) Descriptor() protoreflect.EnumDescriptor {
	return file_live_sites_v1alpha1_database_proto_enumTypes[0].Descriptor()
}

func (BackupState) Type() protoreflect.EnumType {
	return &file_live_sites_v1alpha1_database_proto_enumTypes[0]
}

func (x BackupState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackupState.Descriptor instead.
func (BackupState) EnumDescriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_database_proto_rawDescGZIP(), []int{0}
}

type DatabaseBackup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata *DatabaseBackupMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Content  []byte                  `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CRC32C   string                  `protobuf:"bytes,17,opt,name=CRC32c,proto3" json:"CRC32c,omitempty"`
	MD5      string                  `protobuf:"bytes,18,opt,name=MD5,proto3" json:"MD5,omitempty"`
}

func (x *DatabaseBackup) Reset() {
	*x = DatabaseBackup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_database_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DatabaseBackup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseBackup) ProtoMessage() {}

func (x *DatabaseBackup) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_database_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseBackup.ProtoReflect.Descriptor instead.
func (*DatabaseBackup) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_database_proto_rawDescGZIP(), []int{0}
}

func (x *DatabaseBackup) GetMetadata() *DatabaseBackupMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DatabaseBackup) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *DatabaseBackup) GetCRC32C() string {
	if x != nil {
		return x.CRC32C
	}
	return ""
}

func (x *DatabaseBackup) GetMD5() string {
	if x != nil {
		return x.MD5
	}
	return ""
}

type DatabaseBackupMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name              string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DatabaseReference string      `protobuf:"bytes,2,opt,name=databaseReference,proto3" json:"databaseReference,omitempty"`
	Created           int64       `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	State             BackupState `protobuf:"varint,4,opt,name=state,proto3,enum=ddev.sites.v1alpha1.BackupState" json:"state,omitempty"`
}

func (x *DatabaseBackupMetadata) Reset() {
	*x = DatabaseBackupMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_database_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DatabaseBackupMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseBackupMetadata) ProtoMessage() {}

func (x *DatabaseBackupMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_database_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseBackupMetadata.ProtoReflect.Descriptor instead.
func (*DatabaseBackupMetadata) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_database_proto_rawDescGZIP(), []int{1}
}

func (x *DatabaseBackupMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DatabaseBackupMetadata) GetDatabaseReference() string {
	if x != nil {
		return x.DatabaseReference
	}
	return ""
}

func (x *DatabaseBackupMetadata) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *DatabaseBackupMetadata) GetState() BackupState {
	if x != nil {
		return x.State
	}
	return BackupState_CREATED
}

type BackupDatabaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Site string `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
}

func (x *BackupDatabaseRequest) Reset() {
	*x = BackupDatabaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_database_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupDatabaseRequest) ProtoMessage() {}

func (x *BackupDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_database_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupDatabaseRequest.ProtoReflect.Descriptor instead.
func (*BackupDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_database_proto_rawDescGZIP(), []int{2}
}

func (x *BackupDatabaseRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

type BackupDatabaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Backup *DatabaseBackupMetadata `protobuf:"bytes,1,opt,name=backup,proto3" json:"backup,omitempty"`
}

func (x *BackupDatabaseResponse) Reset() {
	*x = BackupDatabaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_database_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupDatabaseResponse) ProtoMessage() {}

func (x *BackupDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_database_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupDatabaseResponse.ProtoReflect.Descriptor instead.
func (*BackupDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_database_proto_rawDescGZIP(), []int{3}
}

func (x *BackupDatabaseResponse) GetBackup() *DatabaseBackupMetadata {
	if x != nil {
		return x.Backup
	}
	return nil
}

type RestoreDatabaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Site   string `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Backup string `protobuf:"bytes,2,opt,name=backup,proto3" json:"backup,omitempty"`
}

func (x *RestoreDatabaseRequest) Reset() {
	*x = RestoreDatabaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_database_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreDatabaseRequest) ProtoMessage() {}

func (x *RestoreDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_database_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreDatabaseRequest.ProtoReflect.Descriptor instead.
func (*RestoreDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_database_proto_rawDescGZIP(), []int{4}
}

func (x *RestoreDatabaseRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *RestoreDatabaseRequest) GetBackup() string {
	if x != nil {
		return x.Backup
	}
	return ""
}

type RestoreDatabaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Backup *DatabaseBackupMetadata `protobuf:"bytes,1,opt,name=backup,proto3" json:"backup,omitempty"`
}

func (x *RestoreDatabaseResponse) Reset() {
	*x = RestoreDatabaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_database_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreDatabaseResponse) ProtoMessage() {}

func (x *RestoreDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_database_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreDatabaseResponse.ProtoReflect.Descriptor instead.
func (*RestoreDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_database_proto_rawDescGZIP(), []int{5}
}

func (x *RestoreDatabaseResponse) GetBackup() *DatabaseBackupMetadata {
	if x != nil {
		return x.Backup
	}
	return nil
}

type PushDatabaseBackupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Site   string          `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Backup *DatabaseBackup `protobuf:"bytes,2,opt,name=backup,proto3" json:"backup,omitempty"`
}

func (x *PushDatabaseBackupRequest) Reset() {
	*x = PushDatabaseBackupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_database_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushDatabaseBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushDatabaseBackupRequest) ProtoMessage() {}

func (x *PushDatabaseBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_database_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushDatabaseBackupRequest.ProtoReflect.Descriptor instead.
func (*PushDatabaseBackupRequest) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_database_proto_rawDescGZIP(), []int{6}
}

func (x *PushDatabaseBackupRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *PushDatabaseBackupRequest) GetBackup() *DatabaseBackup {
	if x != nil {
		return x.Backup
	}
	return nil
}

type PushDatabaseBackupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Backup string `protobuf:"bytes,1,opt,name=backup,proto3" json:"backup,omitempty"`
}

func (x *PushDatabaseBackupResponse) Reset() {
	*x = PushDatabaseBackupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_database_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushDatabaseBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushDatabaseBackupResponse) ProtoMessage() {}

func (x *PushDatabaseBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_database_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushDatabaseBackupResponse.ProtoReflect.Descriptor instead.
func (*PushDatabaseBackupResponse) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_database_proto_rawDescGZIP(), []int{7}
}

func (x *PushDatabaseBackupResponse) GetBackup() string {
	if x != nil {
		return x.Backup
	}
	return ""
}

type PullDatabaseBackupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Backup string `protobuf:"bytes,1,opt,name=backup,proto3" json:"backup,omitempty"`
}

func (x *PullDatabaseBackupRequest) Reset() {
	*x = PullDatabaseBackupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_database_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullDatabaseBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullDatabaseBackupRequest) ProtoMessage() {}

func (x *PullDatabaseBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_database_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullDatabaseBackupRequest.ProtoReflect.Descriptor instead.
func (*PullDatabaseBackupRequest) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_database_proto_rawDescGZIP(), []int{8}
}

func (x *PullDatabaseBackupRequest) GetBackup() string {
	if x != nil {
		return x.Backup
	}
	return ""
}

type PullDatabaseBackupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Backup *DatabaseBackup `protobuf:"bytes,1,opt,name=backup,proto3" json:"backup,omitempty"`
}

func (x *PullDatabaseBackupResponse) Reset() {
	*x = PullDatabaseBackupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_database_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullDatabaseBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullDatabaseBackupResponse) ProtoMessage() {}

func (x *PullDatabaseBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_database_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullDatabaseBackupResponse.ProtoReflect.Descriptor instead.
func (*PullDatabaseBackupResponse) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_database_proto_rawDescGZIP(), []int{9}
}

func (x *PullDatabaseBackupResponse) GetBackup() *DatabaseBackup {
	if x != nil {
		return x.Backup
	}
	return nil
}

type ListDatabaseBackupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Site string `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
}

func (x *ListDatabaseBackupsRequest) Reset() {
	*x = ListDatabaseBackupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_database_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDatabaseBackupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabaseBackupsRequest) ProtoMessage() {}

func (x *ListDatabaseBackupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_database_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabaseBackupsRequest.ProtoReflect.Descriptor instead.
func (*ListDatabaseBackupsRequest) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_database_proto_rawDescGZIP(), []int{10}
}

func (x *ListDatabaseBackupsRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

type ListDatabaseBackupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Backup []*DatabaseBackupMetadata `protobuf:"bytes,1,rep,name=backup,proto3" json:"backup,omitempty"`
}

func (x *ListDatabaseBackupsResponse) Reset() {
	*x = ListDatabaseBackupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_database_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDatabaseBackupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabaseBackupsResponse) ProtoMessage() {}

func (x *ListDatabaseBackupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_database_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabaseBackupsResponse.ProtoReflect.Descriptor instead.
func (*ListDatabaseBackupsResponse) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_database_proto_rawDescGZIP(), []int{11}
}

func (x *ListDatabaseBackupsResponse) GetBackup() []*DatabaseBackupMetadata {
	if x != nil {
		return x.Backup
	}
	return nil
}

var File_live_sites_v1alpha1_database_proto protoreflect.FileDescriptor

var file_live_sites_v1alpha1_database_proto_rawDesc = []byte{
	0x0a, 0x22, 0x6c, 0x69, 0x76, 0x65, 0x2f, 0x73, 0x69, 0x74, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x73, 0x69, 0x74, 0x65, 0x73,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x22, 0x9d, 0x01, 0x0a, 0x0e, 0x44, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x12, 0x47, 0x0a, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b,
	0x2e, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x73, 0x69, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x42, 0x61, 0x63,
	0x6b, 0x75, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x43, 0x52, 0x43, 0x33, 0x32, 0x63, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x43, 0x52, 0x43, 0x33, 0x32, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x44, 0x35, 0x18, 0x12,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x44, 0x35, 0x22, 0xac, 0x01, 0x0a, 0x16, 0x44, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x64, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x11, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x12, 0x36, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x20, 0x2e, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x73, 0x69, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x2b, 0x0a, 0x15, 0x42, 0x61, 0x63, 0x6b,
	0x75, 0x70, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x73, 0x69, 0x74, 0x65, 0x22, 0x5d, 0x0a, 0x16, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x44,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x43, 0x0a, 0x06, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2b, 0x2e, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x73, 0x69, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x42, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x06, 0x62, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x22, 0x44, 0x0a, 0x16, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69,
	0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x22, 0x5e, 0x0a, 0x17, 0x52, 0x65,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x06, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x73, 0x69, 0x74,
	0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x06, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x22, 0x6c, 0x0a, 0x19, 0x50, 0x75,
	0x73, 0x68, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x74, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x62,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x64, 0x64,
	0x65, 0x76, 0x2e, 0x73, 0x69, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x52, 0x06, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x22, 0x34, 0x0a, 0x1a, 0x50, 0x75, 0x73, 0x68,
	0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x22, 0x33,
	0x0a, 0x19, 0x50, 0x75, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x42, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x61, 0x63,
	0x6b, 0x75, 0x70, 0x22, 0x59, 0x0a, 0x1a, 0x50, 0x75, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3b, 0x0a, 0x06, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x73, 0x69, 0x74, 0x65, 0x73, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x06, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x22, 0x30,
	0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x42, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x74, 0x65,
	0x22, 0x62, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x43, 0x0a, 0x06, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2b, 0x2e, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x73, 0x69, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x42, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x06, 0x62, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x2a, 0x35, 0x0a, 0x0b, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x0c, 0x0a, 0x08, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x02, 0x42, 0x61, 0x0a, 0x1c, 0x63,
	0x6f, 0x6d, 0x2e, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x73, 0x69, 0x74,
	0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x42, 0x0d, 0x44, 0x61, 0x74,
	0x61, 0x62, 0x61, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x30, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x72, 0x75, 0x64, 0x2f, 0x64, 0x64,
	0x65, 0x76, 0x2d, 0x61, 0x70, 0x69, 0x73, 0x2d, 0x67, 0x6f, 0x2f, 0x6c, 0x69, 0x76, 0x65, 0x2f,
	0x73, 0x69, 0x74, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_live_sites_v1alpha1_database_proto_rawDescOnce sync.Once
	file_live_sites_v1alpha1_database_proto_rawDescData = file_live_sites_v1alpha1_database_proto_rawDesc
)

func file_live_sites_v1alpha1_database_proto_rawDescGZIP() []byte {
	file_live_sites_v1alpha1_database_proto_rawDescOnce.Do(func() {
		file_live_sites_v1alpha1_database_proto_rawDescData = protoimpl.X.CompressGZIP(file_live_sites_v1alpha1_database_proto_rawDescData)
	})
	return file_live_sites_v1alpha1_database_proto_rawDescData
}

var file_live_sites_v1alpha1_database_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_live_sites_v1alpha1_database_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_live_sites_v1alpha1_database_proto_goTypes = []interface{}{
	(BackupState)(0),                    // 0: ddev.sites.v1alpha1.BackupState
	(*DatabaseBackup)(nil),              // 1: ddev.sites.v1alpha1.DatabaseBackup
	(*DatabaseBackupMetadata)(nil),      // 2: ddev.sites.v1alpha1.DatabaseBackupMetadata
	(*BackupDatabaseRequest)(nil),       // 3: ddev.sites.v1alpha1.BackupDatabaseRequest
	(*BackupDatabaseResponse)(nil),      // 4: ddev.sites.v1alpha1.BackupDatabaseResponse
	(*RestoreDatabaseRequest)(nil),      // 5: ddev.sites.v1alpha1.RestoreDatabaseRequest
	(*RestoreDatabaseResponse)(nil),     // 6: ddev.sites.v1alpha1.RestoreDatabaseResponse
	(*PushDatabaseBackupRequest)(nil),   // 7: ddev.sites.v1alpha1.PushDatabaseBackupRequest
	(*PushDatabaseBackupResponse)(nil),  // 8: ddev.sites.v1alpha1.PushDatabaseBackupResponse
	(*PullDatabaseBackupRequest)(nil),   // 9: ddev.sites.v1alpha1.PullDatabaseBackupRequest
	(*PullDatabaseBackupResponse)(nil),  // 10: ddev.sites.v1alpha1.PullDatabaseBackupResponse
	(*ListDatabaseBackupsRequest)(nil),  // 11: ddev.sites.v1alpha1.ListDatabaseBackupsRequest
	(*ListDatabaseBackupsResponse)(nil), // 12: ddev.sites.v1alpha1.ListDatabaseBackupsResponse
}
var file_live_sites_v1alpha1_database_proto_depIdxs = []int32{
	2, // 0: ddev.sites.v1alpha1.DatabaseBackup.metadata:type_name -> ddev.sites.v1alpha1.DatabaseBackupMetadata
	0, // 1: ddev.sites.v1alpha1.DatabaseBackupMetadata.state:type_name -> ddev.sites.v1alpha1.BackupState
	2, // 2: ddev.sites.v1alpha1.BackupDatabaseResponse.backup:type_name -> ddev.sites.v1alpha1.DatabaseBackupMetadata
	2, // 3: ddev.sites.v1alpha1.RestoreDatabaseResponse.backup:type_name -> ddev.sites.v1alpha1.DatabaseBackupMetadata
	1, // 4: ddev.sites.v1alpha1.PushDatabaseBackupRequest.backup:type_name -> ddev.sites.v1alpha1.DatabaseBackup
	1, // 5: ddev.sites.v1alpha1.PullDatabaseBackupResponse.backup:type_name -> ddev.sites.v1alpha1.DatabaseBackup
	2, // 6: ddev.sites.v1alpha1.ListDatabaseBackupsResponse.backup:type_name -> ddev.sites.v1alpha1.DatabaseBackupMetadata
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_live_sites_v1alpha1_database_proto_init() }
func file_live_sites_v1alpha1_database_proto_init() {
	if File_live_sites_v1alpha1_database_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_live_sites_v1alpha1_database_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DatabaseBackup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_database_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DatabaseBackupMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_database_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupDatabaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_database_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupDatabaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_database_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreDatabaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_database_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreDatabaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_database_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushDatabaseBackupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_database_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushDatabaseBackupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_database_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullDatabaseBackupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_database_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullDatabaseBackupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_database_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDatabaseBackupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_database_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDatabaseBackupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_live_sites_v1alpha1_database_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_live_sites_v1alpha1_database_proto_goTypes,
		DependencyIndexes: file_live_sites_v1alpha1_database_proto_depIdxs,
		EnumInfos:         file_live_sites_v1alpha1_database_proto_enumTypes,
		MessageInfos:      file_live_sites_v1alpha1_database_proto_msgTypes,
	}.Build()
	File_live_sites_v1alpha1_database_proto = out.File
	file_live_sites_v1alpha1_database_proto_rawDesc = nil
	file_live_sites_v1alpha1_database_proto_goTypes = nil
	file_live_sites_v1alpha1_database_proto_depIdxs = nil
}
