// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.0
// source: live/sites/v1alpha1/file.proto

package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FileBackupMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name              string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DatabaseReference string `protobuf:"bytes,2,opt,name=databaseReference,proto3" json:"databaseReference,omitempty"`
	Created           int64  `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *FileBackupMetadata) Reset() {
	*x = FileBackupMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_file_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileBackupMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileBackupMetadata) ProtoMessage() {}

func (x *FileBackupMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_file_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileBackupMetadata.ProtoReflect.Descriptor instead.
func (*FileBackupMetadata) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_file_proto_rawDescGZIP(), []int{0}
}

func (x *FileBackupMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileBackupMetadata) GetDatabaseReference() string {
	if x != nil {
		return x.DatabaseReference
	}
	return ""
}

func (x *FileBackupMetadata) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CRC32C  string `protobuf:"bytes,17,opt,name=CRC32c,proto3" json:"CRC32c,omitempty"`
	MD5     string `protobuf:"bytes,18,opt,name=MD5,proto3" json:"MD5,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_file_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_file_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_file_proto_rawDescGZIP(), []int{1}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *File) GetCRC32C() string {
	if x != nil {
		return x.CRC32C
	}
	return ""
}

func (x *File) GetMD5() string {
	if x != nil {
		return x.MD5
	}
	return ""
}

type FileBackup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata *FileBackupMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Files    []*File             `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *FileBackup) Reset() {
	*x = FileBackup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_file_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileBackup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileBackup) ProtoMessage() {}

func (x *FileBackup) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_file_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileBackup.ProtoReflect.Descriptor instead.
func (*FileBackup) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_file_proto_rawDescGZIP(), []int{2}
}

func (x *FileBackup) GetMetadata() *FileBackupMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *FileBackup) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

type BackupFilesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Site string `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
}

func (x *BackupFilesRequest) Reset() {
	*x = BackupFilesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_file_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupFilesRequest) ProtoMessage() {}

func (x *BackupFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_file_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupFilesRequest.ProtoReflect.Descriptor instead.
func (*BackupFilesRequest) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_file_proto_rawDescGZIP(), []int{3}
}

func (x *BackupFilesRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

type BackupFilesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *BackupFilesResponse) Reset() {
	*x = BackupFilesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_file_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupFilesResponse) ProtoMessage() {}

func (x *BackupFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_file_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupFilesResponse.ProtoReflect.Descriptor instead.
func (*BackupFilesResponse) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_file_proto_rawDescGZIP(), []int{4}
}

func (x *BackupFilesResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RestoreFilesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Site string `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
}

func (x *RestoreFilesRequest) Reset() {
	*x = RestoreFilesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_file_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFilesRequest) ProtoMessage() {}

func (x *RestoreFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_file_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFilesRequest.ProtoReflect.Descriptor instead.
func (*RestoreFilesRequest) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_file_proto_rawDescGZIP(), []int{5}
}

func (x *RestoreFilesRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

type RestoreFilesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RestoreFilesResponse) Reset() {
	*x = RestoreFilesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_file_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFilesResponse) ProtoMessage() {}

func (x *RestoreFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_file_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFilesResponse.ProtoReflect.Descriptor instead.
func (*RestoreFilesResponse) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_file_proto_rawDescGZIP(), []int{6}
}

func (x *RestoreFilesResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PushFileBackupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Site      string `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	File      *File  `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Directory string `protobuf:"bytes,17,opt,name=directory,proto3" json:"directory,omitempty"`
}

func (x *PushFileBackupRequest) Reset() {
	*x = PushFileBackupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_file_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushFileBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFileBackupRequest) ProtoMessage() {}

func (x *PushFileBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_file_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFileBackupRequest.ProtoReflect.Descriptor instead.
func (*PushFileBackupRequest) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_file_proto_rawDescGZIP(), []int{7}
}

func (x *PushFileBackupRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *PushFileBackupRequest) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *PushFileBackupRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

type PushFileBackupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PushFileBackupResponse) Reset() {
	*x = PushFileBackupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_file_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushFileBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFileBackupResponse) ProtoMessage() {}

func (x *PushFileBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_file_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFileBackupResponse.ProtoReflect.Descriptor instead.
func (*PushFileBackupResponse) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_file_proto_rawDescGZIP(), []int{8}
}

func (x *PushFileBackupResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PullFileBackupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Site  string   `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Paths []string `protobuf:"bytes,17,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *PullFileBackupRequest) Reset() {
	*x = PullFileBackupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_file_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullFileBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullFileBackupRequest) ProtoMessage() {}

func (x *PullFileBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_file_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullFileBackupRequest.ProtoReflect.Descriptor instead.
func (*PullFileBackupRequest) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_file_proto_rawDescGZIP(), []int{9}
}

func (x *PullFileBackupRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *PullFileBackupRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type PullFileBackupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File *File `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *PullFileBackupResponse) Reset() {
	*x = PullFileBackupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_file_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullFileBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullFileBackupResponse) ProtoMessage() {}

func (x *PullFileBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_file_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullFileBackupResponse.ProtoReflect.Descriptor instead.
func (*PullFileBackupResponse) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_file_proto_rawDescGZIP(), []int{10}
}

func (x *PullFileBackupResponse) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

type DescribeFileBackupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Site  string   `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Paths []string `protobuf:"bytes,17,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *DescribeFileBackupRequest) Reset() {
	*x = DescribeFileBackupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_file_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeFileBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeFileBackupRequest) ProtoMessage() {}

func (x *DescribeFileBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_file_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeFileBackupRequest.ProtoReflect.Descriptor instead.
func (*DescribeFileBackupRequest) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_file_proto_rawDescGZIP(), []int{11}
}

func (x *DescribeFileBackupRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *DescribeFileBackupRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type DescribeFileBackupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata []*File `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *DescribeFileBackupResponse) Reset() {
	*x = DescribeFileBackupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_file_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeFileBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeFileBackupResponse) ProtoMessage() {}

func (x *DescribeFileBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_file_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeFileBackupResponse.ProtoReflect.Descriptor instead.
func (*DescribeFileBackupResponse) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_file_proto_rawDescGZIP(), []int{12}
}

func (x *DescribeFileBackupResponse) GetMetadata() []*File {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ListFileBackupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Site string `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
}

func (x *ListFileBackupsRequest) Reset() {
	*x = ListFileBackupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_file_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFileBackupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFileBackupsRequest) ProtoMessage() {}

func (x *ListFileBackupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_file_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFileBackupsRequest.ProtoReflect.Descriptor instead.
func (*ListFileBackupsRequest) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_file_proto_rawDescGZIP(), []int{13}
}

func (x *ListFileBackupsRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

type ListFileBackupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata []*FileBackupMetadata `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *ListFileBackupsResponse) Reset() {
	*x = ListFileBackupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_sites_v1alpha1_file_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFileBackupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFileBackupsResponse) ProtoMessage() {}

func (x *ListFileBackupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_sites_v1alpha1_file_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFileBackupsResponse.ProtoReflect.Descriptor instead.
func (*ListFileBackupsResponse) Descriptor() ([]byte, []int) {
	return file_live_sites_v1alpha1_file_proto_rawDescGZIP(), []int{14}
}

func (x *ListFileBackupsResponse) GetMetadata() []*FileBackupMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_live_sites_v1alpha1_file_proto protoreflect.FileDescriptor

var file_live_sites_v1alpha1_file_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6c, 0x69, 0x76, 0x65, 0x2f, 0x73, 0x69, 0x74, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x13, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x73, 0x69, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x22, 0x70, 0x0a, 0x12, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x61, 0x63,
	0x6b, 0x75, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x2c, 0x0a, 0x11, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x64, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0x5e, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x43, 0x52, 0x43, 0x33, 0x32, 0x63, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43,
	0x52, 0x43, 0x33, 0x32, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x44, 0x35, 0x18, 0x12, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x4d, 0x44, 0x35, 0x22, 0x82, 0x01, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x65,
	0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x12, 0x43, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x64, 0x64, 0x65, 0x76, 0x2e,
	0x73, 0x69, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2f, 0x0a, 0x05, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x64, 0x65,
	0x76, 0x2e, 0x73, 0x69, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x12,
	0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x73, 0x69, 0x74, 0x65, 0x22, 0x29, 0x0a, 0x13, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x29, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x74, 0x65, 0x22, 0x2a, 0x0a, 0x14,
	0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x78, 0x0a, 0x15, 0x50, 0x75, 0x73, 0x68,
	0x46, 0x69, 0x6c, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x73, 0x69, 0x74, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x73, 0x69, 0x74, 0x65, 0x73,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x79, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x79, 0x22, 0x2c, 0x0a, 0x16, 0x50, 0x75, 0x73, 0x68, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x41, 0x0a, 0x15, 0x50, 0x75, 0x6c, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x61, 0x63, 0x6b,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x74, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x18, 0x11, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61,
	0x74, 0x68, 0x73, 0x22, 0x47, 0x0a, 0x16, 0x50, 0x75, 0x6c, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x42,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a,
	0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x64,
	0x65, 0x76, 0x2e, 0x73, 0x69, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x45, 0x0a, 0x19,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x61, 0x63, 0x6b,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x74, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x18, 0x11, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61,
	0x74, 0x68, 0x73, 0x22, 0x53, 0x0a, 0x1a, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x46,
	0x69, 0x6c, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x35, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x73, 0x69, 0x74, 0x65, 0x73,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2c, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74,
	0x46, 0x69, 0x6c, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x73, 0x69, 0x74, 0x65, 0x22, 0x5e, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x43, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x73, 0x69, 0x74, 0x65, 0x73,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x42, 0x5d, 0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x2e, 0x64, 0x64,
	0x65, 0x76, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x73, 0x69, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x42, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x64, 0x72, 0x75, 0x64, 0x2f, 0x64, 0x64, 0x65, 0x76, 0x2d, 0x61, 0x70, 0x69, 0x73, 0x2d, 0x67,
	0x6f, 0x2f, 0x6c, 0x69, 0x76, 0x65, 0x2f, 0x73, 0x69, 0x74, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_live_sites_v1alpha1_file_proto_rawDescOnce sync.Once
	file_live_sites_v1alpha1_file_proto_rawDescData = file_live_sites_v1alpha1_file_proto_rawDesc
)

func file_live_sites_v1alpha1_file_proto_rawDescGZIP() []byte {
	file_live_sites_v1alpha1_file_proto_rawDescOnce.Do(func() {
		file_live_sites_v1alpha1_file_proto_rawDescData = protoimpl.X.CompressGZIP(file_live_sites_v1alpha1_file_proto_rawDescData)
	})
	return file_live_sites_v1alpha1_file_proto_rawDescData
}

var file_live_sites_v1alpha1_file_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_live_sites_v1alpha1_file_proto_goTypes = []interface{}{
	(*FileBackupMetadata)(nil),         // 0: ddev.sites.v1alpha1.FileBackupMetadata
	(*File)(nil),                       // 1: ddev.sites.v1alpha1.File
	(*FileBackup)(nil),                 // 2: ddev.sites.v1alpha1.FileBackup
	(*BackupFilesRequest)(nil),         // 3: ddev.sites.v1alpha1.BackupFilesRequest
	(*BackupFilesResponse)(nil),        // 4: ddev.sites.v1alpha1.BackupFilesResponse
	(*RestoreFilesRequest)(nil),        // 5: ddev.sites.v1alpha1.RestoreFilesRequest
	(*RestoreFilesResponse)(nil),       // 6: ddev.sites.v1alpha1.RestoreFilesResponse
	(*PushFileBackupRequest)(nil),      // 7: ddev.sites.v1alpha1.PushFileBackupRequest
	(*PushFileBackupResponse)(nil),     // 8: ddev.sites.v1alpha1.PushFileBackupResponse
	(*PullFileBackupRequest)(nil),      // 9: ddev.sites.v1alpha1.PullFileBackupRequest
	(*PullFileBackupResponse)(nil),     // 10: ddev.sites.v1alpha1.PullFileBackupResponse
	(*DescribeFileBackupRequest)(nil),  // 11: ddev.sites.v1alpha1.DescribeFileBackupRequest
	(*DescribeFileBackupResponse)(nil), // 12: ddev.sites.v1alpha1.DescribeFileBackupResponse
	(*ListFileBackupsRequest)(nil),     // 13: ddev.sites.v1alpha1.ListFileBackupsRequest
	(*ListFileBackupsResponse)(nil),    // 14: ddev.sites.v1alpha1.ListFileBackupsResponse
}
var file_live_sites_v1alpha1_file_proto_depIdxs = []int32{
	0, // 0: ddev.sites.v1alpha1.FileBackup.metadata:type_name -> ddev.sites.v1alpha1.FileBackupMetadata
	1, // 1: ddev.sites.v1alpha1.FileBackup.files:type_name -> ddev.sites.v1alpha1.File
	1, // 2: ddev.sites.v1alpha1.PushFileBackupRequest.file:type_name -> ddev.sites.v1alpha1.File
	1, // 3: ddev.sites.v1alpha1.PullFileBackupResponse.file:type_name -> ddev.sites.v1alpha1.File
	1, // 4: ddev.sites.v1alpha1.DescribeFileBackupResponse.metadata:type_name -> ddev.sites.v1alpha1.File
	0, // 5: ddev.sites.v1alpha1.ListFileBackupsResponse.metadata:type_name -> ddev.sites.v1alpha1.FileBackupMetadata
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_live_sites_v1alpha1_file_proto_init() }
func file_live_sites_v1alpha1_file_proto_init() {
	if File_live_sites_v1alpha1_file_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_live_sites_v1alpha1_file_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileBackupMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_file_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_file_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileBackup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_file_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupFilesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_file_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupFilesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_file_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreFilesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_file_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreFilesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_file_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushFileBackupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_file_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushFileBackupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_file_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullFileBackupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_file_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullFileBackupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_file_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeFileBackupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_file_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeFileBackupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_file_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFileBackupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_sites_v1alpha1_file_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFileBackupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_live_sites_v1alpha1_file_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_live_sites_v1alpha1_file_proto_goTypes,
		DependencyIndexes: file_live_sites_v1alpha1_file_proto_depIdxs,
		MessageInfos:      file_live_sites_v1alpha1_file_proto_msgTypes,
	}.Build()
	File_live_sites_v1alpha1_file_proto = out.File
	file_live_sites_v1alpha1_file_proto_rawDesc = nil
	file_live_sites_v1alpha1_file_proto_goTypes = nil
	file_live_sites_v1alpha1_file_proto_depIdxs = nil
}
