// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.0
// source: live/administration/v1alpha1/githubintegration.proto

package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GithubIntegrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstallationID int64  `protobuf:"varint,1,opt,name=installationID,proto3" json:"installationID,omitempty"`
	GithubAppID    int64  `protobuf:"varint,2,opt,name=githubAppID,proto3" json:"githubAppID,omitempty"`
	GithubAppSlug  string `protobuf:"bytes,16,opt,name=githubAppSlug,proto3" json:"githubAppSlug,omitempty"`
}

func (x *GithubIntegrationRequest) Reset() {
	*x = GithubIntegrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GithubIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubIntegrationRequest) ProtoMessage() {}

func (x *GithubIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubIntegrationRequest.ProtoReflect.Descriptor instead.
func (*GithubIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_githubintegration_proto_rawDescGZIP(), []int{0}
}

func (x *GithubIntegrationRequest) GetInstallationID() int64 {
	if x != nil {
		return x.InstallationID
	}
	return 0
}

func (x *GithubIntegrationRequest) GetGithubAppID() int64 {
	if x != nil {
		return x.GithubAppID
	}
	return 0
}

func (x *GithubIntegrationRequest) GetGithubAppSlug() string {
	if x != nil {
		return x.GithubAppSlug
	}
	return ""
}

type GithubIntegrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstallationID int64 `protobuf:"varint,1,opt,name=installationID,proto3" json:"installationID,omitempty"`
	GithubAppID    int64 `protobuf:"varint,2,opt,name=githubAppID,proto3" json:"githubAppID,omitempty"`
}

func (x *GithubIntegrationResponse) Reset() {
	*x = GithubIntegrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GithubIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubIntegrationResponse) ProtoMessage() {}

func (x *GithubIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubIntegrationResponse.ProtoReflect.Descriptor instead.
func (*GithubIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_githubintegration_proto_rawDescGZIP(), []int{1}
}

func (x *GithubIntegrationResponse) GetInstallationID() int64 {
	if x != nil {
		return x.InstallationID
	}
	return 0
}

func (x *GithubIntegrationResponse) GetGithubAppID() int64 {
	if x != nil {
		return x.GithubAppID
	}
	return 0
}

type CreateGithubIntegrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Integration *GithubIntegrationRequest `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
}

func (x *CreateGithubIntegrationRequest) Reset() {
	*x = CreateGithubIntegrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGithubIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGithubIntegrationRequest) ProtoMessage() {}

func (x *CreateGithubIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGithubIntegrationRequest.ProtoReflect.Descriptor instead.
func (*CreateGithubIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_githubintegration_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGithubIntegrationRequest) GetIntegration() *GithubIntegrationRequest {
	if x != nil {
		return x.Integration
	}
	return nil
}

type CreateGithubIntegrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Integration *GithubIntegrationResponse `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
}

func (x *CreateGithubIntegrationResponse) Reset() {
	*x = CreateGithubIntegrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGithubIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGithubIntegrationResponse) ProtoMessage() {}

func (x *CreateGithubIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGithubIntegrationResponse.ProtoReflect.Descriptor instead.
func (*CreateGithubIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_githubintegration_proto_rawDescGZIP(), []int{3}
}

func (x *CreateGithubIntegrationResponse) GetIntegration() *GithubIntegrationResponse {
	if x != nil {
		return x.Integration
	}
	return nil
}

type DeleteGithubIntegrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Integration *GithubIntegrationRequest `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
}

func (x *DeleteGithubIntegrationRequest) Reset() {
	*x = DeleteGithubIntegrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGithubIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGithubIntegrationRequest) ProtoMessage() {}

func (x *DeleteGithubIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGithubIntegrationRequest.ProtoReflect.Descriptor instead.
func (*DeleteGithubIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_githubintegration_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteGithubIntegrationRequest) GetIntegration() *GithubIntegrationRequest {
	if x != nil {
		return x.Integration
	}
	return nil
}

type DeleteGithubIntegrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Integration *GithubIntegrationResponse `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
}

func (x *DeleteGithubIntegrationResponse) Reset() {
	*x = DeleteGithubIntegrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGithubIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGithubIntegrationResponse) ProtoMessage() {}

func (x *DeleteGithubIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGithubIntegrationResponse.ProtoReflect.Descriptor instead.
func (*DeleteGithubIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_githubintegration_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteGithubIntegrationResponse) GetIntegration() *GithubIntegrationResponse {
	if x != nil {
		return x.Integration
	}
	return nil
}

type UpdateGithubIntegrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Integration *GithubIntegrationRequest `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
}

func (x *UpdateGithubIntegrationRequest) Reset() {
	*x = UpdateGithubIntegrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGithubIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGithubIntegrationRequest) ProtoMessage() {}

func (x *UpdateGithubIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGithubIntegrationRequest.ProtoReflect.Descriptor instead.
func (*UpdateGithubIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_githubintegration_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateGithubIntegrationRequest) GetIntegration() *GithubIntegrationRequest {
	if x != nil {
		return x.Integration
	}
	return nil
}

type UpdateGithubIntegrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Integration *GithubIntegrationResponse `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
}

func (x *UpdateGithubIntegrationResponse) Reset() {
	*x = UpdateGithubIntegrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGithubIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGithubIntegrationResponse) ProtoMessage() {}

func (x *UpdateGithubIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGithubIntegrationResponse.ProtoReflect.Descriptor instead.
func (*UpdateGithubIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_githubintegration_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateGithubIntegrationResponse) GetIntegration() *GithubIntegrationResponse {
	if x != nil {
		return x.Integration
	}
	return nil
}

type GithubRepositoryReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sha string `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`
	// Types that are assignable to Type:
	//	*GithubRepositoryReference_Branch
	//	*GithubRepositoryReference_Tag
	//	*GithubRepositoryReference_Pullrequest
	Type isGithubRepositoryReference_Type `protobuf_oneof:"type"`
}

func (x *GithubRepositoryReference) Reset() {
	*x = GithubRepositoryReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GithubRepositoryReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubRepositoryReference) ProtoMessage() {}

func (x *GithubRepositoryReference) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubRepositoryReference.ProtoReflect.Descriptor instead.
func (*GithubRepositoryReference) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_githubintegration_proto_rawDescGZIP(), []int{8}
}

func (x *GithubRepositoryReference) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (m *GithubRepositoryReference) GetType() isGithubRepositoryReference_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *GithubRepositoryReference) GetBranch() string {
	if x, ok := x.GetType().(*GithubRepositoryReference_Branch); ok {
		return x.Branch
	}
	return ""
}

func (x *GithubRepositoryReference) GetTag() string {
	if x, ok := x.GetType().(*GithubRepositoryReference_Tag); ok {
		return x.Tag
	}
	return ""
}

func (x *GithubRepositoryReference) GetPullrequest() string {
	if x, ok := x.GetType().(*GithubRepositoryReference_Pullrequest); ok {
		return x.Pullrequest
	}
	return ""
}

type isGithubRepositoryReference_Type interface {
	isGithubRepositoryReference_Type()
}

type GithubRepositoryReference_Branch struct {
	Branch string `protobuf:"bytes,10,opt,name=branch,proto3,oneof"`
}

type GithubRepositoryReference_Tag struct {
	Tag string `protobuf:"bytes,11,opt,name=tag,proto3,oneof"`
}

type GithubRepositoryReference_Pullrequest struct {
	Pullrequest string `protobuf:"bytes,12,opt,name=pullrequest,proto3,oneof"`
}

func (*GithubRepositoryReference_Branch) isGithubRepositoryReference_Type() {}

func (*GithubRepositoryReference_Tag) isGithubRepositoryReference_Type() {}

func (*GithubRepositoryReference_Pullrequest) isGithubRepositoryReference_Type() {}

type GithubRepositoryOwner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Repositories   []*GithubRepositoryName `protobuf:"bytes,2,rep,name=repositories,proto3" json:"repositories,omitempty"`
	InstallationID string                  `protobuf:"bytes,3,opt,name=installationID,proto3" json:"installationID,omitempty"`
}

func (x *GithubRepositoryOwner) Reset() {
	*x = GithubRepositoryOwner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GithubRepositoryOwner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubRepositoryOwner) ProtoMessage() {}

func (x *GithubRepositoryOwner) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubRepositoryOwner.ProtoReflect.Descriptor instead.
func (*GithubRepositoryOwner) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_githubintegration_proto_rawDescGZIP(), []int{9}
}

func (x *GithubRepositoryOwner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GithubRepositoryOwner) GetRepositories() []*GithubRepositoryName {
	if x != nil {
		return x.Repositories
	}
	return nil
}

func (x *GithubRepositoryOwner) GetInstallationID() string {
	if x != nil {
		return x.InstallationID
	}
	return ""
}

type GithubRepositoryName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GithubRepositoryName) Reset() {
	*x = GithubRepositoryName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GithubRepositoryName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubRepositoryName) ProtoMessage() {}

func (x *GithubRepositoryName) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubRepositoryName.ProtoReflect.Descriptor instead.
func (*GithubRepositoryName) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_githubintegration_proto_rawDescGZIP(), []int{10}
}

func (x *GithubRepositoryName) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GithubRepositoryName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListGithubRepositoriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListGithubRepositoriesRequest) Reset() {
	*x = ListGithubRepositoriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGithubRepositoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGithubRepositoriesRequest) ProtoMessage() {}

func (x *ListGithubRepositoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGithubRepositoriesRequest.ProtoReflect.Descriptor instead.
func (*ListGithubRepositoriesRequest) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_githubintegration_proto_rawDescGZIP(), []int{11}
}

type ListGithubRepositoriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*GithubRepositoryOwner `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListGithubRepositoriesResponse) Reset() {
	*x = ListGithubRepositoriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGithubRepositoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGithubRepositoriesResponse) ProtoMessage() {}

func (x *ListGithubRepositoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGithubRepositoriesResponse.ProtoReflect.Descriptor instead.
func (*ListGithubRepositoriesResponse) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_githubintegration_proto_rawDescGZIP(), []int{12}
}

func (x *ListGithubRepositoriesResponse) GetItems() []*GithubRepositoryOwner {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetRepositoryMetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner string `protobuf:"bytes,16,opt,name=owner,proto3" json:"owner,omitempty"`
	Name  string `protobuf:"bytes,17,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetRepositoryMetadataRequest) Reset() {
	*x = GetRepositoryMetadataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRepositoryMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryMetadataRequest) ProtoMessage() {}

func (x *GetRepositoryMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetRepositoryMetadataRequest) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_githubintegration_proto_rawDescGZIP(), []int{13}
}

func (x *GetRepositoryMetadataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetRepositoryMetadataRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GetRepositoryMetadataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetRepositoryMetadataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner string                       `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Name  string                       `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Meta  []*GithubRepositoryReference `protobuf:"bytes,4,rep,name=meta,proto3" json:"meta,omitempty"`
}

func (x *GetRepositoryMetadataResponse) Reset() {
	*x = GetRepositoryMetadataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRepositoryMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryMetadataResponse) ProtoMessage() {}

func (x *GetRepositoryMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_githubintegration_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetRepositoryMetadataResponse) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_githubintegration_proto_rawDescGZIP(), []int{14}
}

func (x *GetRepositoryMetadataResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetRepositoryMetadataResponse) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GetRepositoryMetadataResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRepositoryMetadataResponse) GetMeta() []*GithubRepositoryReference {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_live_administration_v1alpha1_githubintegration_proto protoreflect.FileDescriptor

var file_live_administration_v1alpha1_githubintegration_proto_rawDesc = []byte{
	0x0a, 0x34, 0x6c, 0x69, 0x76, 0x65, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x22, 0x8a, 0x01, 0x0a, 0x18, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x49,
	0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x26, 0x0a, 0x0e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x41, 0x70, 0x70, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x41, 0x70, 0x70, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x41, 0x70, 0x70, 0x53, 0x6c, 0x75, 0x67, 0x18, 0x10, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x41, 0x70, 0x70, 0x53, 0x6c, 0x75,
	0x67, 0x22, 0x65, 0x0a, 0x19, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x49, 0x6e, 0x74, 0x65, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26,
	0x0a, 0x0e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x41, 0x70, 0x70, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x41, 0x70, 0x70, 0x49, 0x44, 0x22, 0x7a, 0x0a, 0x1e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x58, 0x0a, 0x0b, 0x69, 0x6e,
	0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x36, 0x2e, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x47,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x7c, 0x0a, 0x1f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x64,
	0x64, 0x65, 0x76, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x47, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x7a, 0x0a, 0x1e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x58, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x64, 0x64, 0x65, 0x76,
	0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x49,
	0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x7c,
	0x0a, 0x1f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x49, 0x6e,
	0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x59, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x49, 0x6e, 0x74, 0x65,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x7a, 0x0a, 0x1e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x49, 0x6e, 0x74, 0x65,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x58,
	0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2e, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x69, 0x6e, 0x74,
	0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x7c, 0x0a, 0x1f, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0b, 0x69,
	0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x37, 0x2e, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x87, 0x01, 0x0a, 0x19, 0x47, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x68, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x73, 0x68, 0x61, 0x12, 0x18, 0x0a, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x12, 0x12, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x03, 0x74, 0x61, 0x67, 0x12, 0x22, 0x0a, 0x0b, 0x70, 0x75, 0x6c, 0x6c, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x70, 0x75, 0x6c,
	0x6c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0xab, 0x01, 0x0a, 0x15, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x52, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x6f, 0x72, 0x79, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x56,
	0x0a, 0x0c, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2e, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x0c, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0x3a,
	0x0a, 0x14, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f,
	0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1f, 0x0a, 0x1d, 0x4c, 0x69,
	0x73, 0x74, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6b, 0x0a, 0x1e, 0x4c,
	0x69, 0x73, 0x74, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x64,
	0x64, 0x65, 0x76, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x47, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x58, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0xa6, 0x01, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x6f, 0x72, 0x79, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x4b,
	0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x64,
	0x64, 0x65, 0x76, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x47, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x42, 0x7c, 0x0a, 0x25, 0x63,
	0x6f, 0x6d, 0x2e, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x42, 0x16, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x49, 0x6e, 0x74, 0x65,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x39,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x72, 0x75, 0x64, 0x2f,
	0x64, 0x64, 0x65, 0x76, 0x2d, 0x61, 0x70, 0x69, 0x73, 0x2d, 0x67, 0x6f, 0x2f, 0x6c, 0x69, 0x76,
	0x65, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_live_administration_v1alpha1_githubintegration_proto_rawDescOnce sync.Once
	file_live_administration_v1alpha1_githubintegration_proto_rawDescData = file_live_administration_v1alpha1_githubintegration_proto_rawDesc
)

func file_live_administration_v1alpha1_githubintegration_proto_rawDescGZIP() []byte {
	file_live_administration_v1alpha1_githubintegration_proto_rawDescOnce.Do(func() {
		file_live_administration_v1alpha1_githubintegration_proto_rawDescData = protoimpl.X.CompressGZIP(file_live_administration_v1alpha1_githubintegration_proto_rawDescData)
	})
	return file_live_administration_v1alpha1_githubintegration_proto_rawDescData
}

var file_live_administration_v1alpha1_githubintegration_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_live_administration_v1alpha1_githubintegration_proto_goTypes = []interface{}{
	(*GithubIntegrationRequest)(nil),        // 0: ddev.administration.v1alpha1.GithubIntegrationRequest
	(*GithubIntegrationResponse)(nil),       // 1: ddev.administration.v1alpha1.GithubIntegrationResponse
	(*CreateGithubIntegrationRequest)(nil),  // 2: ddev.administration.v1alpha1.CreateGithubIntegrationRequest
	(*CreateGithubIntegrationResponse)(nil), // 3: ddev.administration.v1alpha1.CreateGithubIntegrationResponse
	(*DeleteGithubIntegrationRequest)(nil),  // 4: ddev.administration.v1alpha1.DeleteGithubIntegrationRequest
	(*DeleteGithubIntegrationResponse)(nil), // 5: ddev.administration.v1alpha1.DeleteGithubIntegrationResponse
	(*UpdateGithubIntegrationRequest)(nil),  // 6: ddev.administration.v1alpha1.UpdateGithubIntegrationRequest
	(*UpdateGithubIntegrationResponse)(nil), // 7: ddev.administration.v1alpha1.UpdateGithubIntegrationResponse
	(*GithubRepositoryReference)(nil),       // 8: ddev.administration.v1alpha1.GithubRepositoryReference
	(*GithubRepositoryOwner)(nil),           // 9: ddev.administration.v1alpha1.GithubRepositoryOwner
	(*GithubRepositoryName)(nil),            // 10: ddev.administration.v1alpha1.GithubRepositoryName
	(*ListGithubRepositoriesRequest)(nil),   // 11: ddev.administration.v1alpha1.ListGithubRepositoriesRequest
	(*ListGithubRepositoriesResponse)(nil),  // 12: ddev.administration.v1alpha1.ListGithubRepositoriesResponse
	(*GetRepositoryMetadataRequest)(nil),    // 13: ddev.administration.v1alpha1.GetRepositoryMetadataRequest
	(*GetRepositoryMetadataResponse)(nil),   // 14: ddev.administration.v1alpha1.GetRepositoryMetadataResponse
}
var file_live_administration_v1alpha1_githubintegration_proto_depIdxs = []int32{
	0,  // 0: ddev.administration.v1alpha1.CreateGithubIntegrationRequest.integration:type_name -> ddev.administration.v1alpha1.GithubIntegrationRequest
	1,  // 1: ddev.administration.v1alpha1.CreateGithubIntegrationResponse.integration:type_name -> ddev.administration.v1alpha1.GithubIntegrationResponse
	0,  // 2: ddev.administration.v1alpha1.DeleteGithubIntegrationRequest.integration:type_name -> ddev.administration.v1alpha1.GithubIntegrationRequest
	1,  // 3: ddev.administration.v1alpha1.DeleteGithubIntegrationResponse.integration:type_name -> ddev.administration.v1alpha1.GithubIntegrationResponse
	0,  // 4: ddev.administration.v1alpha1.UpdateGithubIntegrationRequest.integration:type_name -> ddev.administration.v1alpha1.GithubIntegrationRequest
	1,  // 5: ddev.administration.v1alpha1.UpdateGithubIntegrationResponse.integration:type_name -> ddev.administration.v1alpha1.GithubIntegrationResponse
	10, // 6: ddev.administration.v1alpha1.GithubRepositoryOwner.repositories:type_name -> ddev.administration.v1alpha1.GithubRepositoryName
	9,  // 7: ddev.administration.v1alpha1.ListGithubRepositoriesResponse.items:type_name -> ddev.administration.v1alpha1.GithubRepositoryOwner
	8,  // 8: ddev.administration.v1alpha1.GetRepositoryMetadataResponse.meta:type_name -> ddev.administration.v1alpha1.GithubRepositoryReference
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_live_administration_v1alpha1_githubintegration_proto_init() }
func file_live_administration_v1alpha1_githubintegration_proto_init() {
	if File_live_administration_v1alpha1_githubintegration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_live_administration_v1alpha1_githubintegration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GithubIntegrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_githubintegration_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GithubIntegrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_githubintegration_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGithubIntegrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_githubintegration_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGithubIntegrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_githubintegration_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGithubIntegrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_githubintegration_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGithubIntegrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_githubintegration_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGithubIntegrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_githubintegration_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGithubIntegrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_githubintegration_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GithubRepositoryReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_githubintegration_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GithubRepositoryOwner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_githubintegration_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GithubRepositoryName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_githubintegration_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGithubRepositoriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_githubintegration_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGithubRepositoriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_githubintegration_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRepositoryMetadataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_githubintegration_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRepositoryMetadataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_live_administration_v1alpha1_githubintegration_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*GithubRepositoryReference_Branch)(nil),
		(*GithubRepositoryReference_Tag)(nil),
		(*GithubRepositoryReference_Pullrequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_live_administration_v1alpha1_githubintegration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_live_administration_v1alpha1_githubintegration_proto_goTypes,
		DependencyIndexes: file_live_administration_v1alpha1_githubintegration_proto_depIdxs,
		MessageInfos:      file_live_administration_v1alpha1_githubintegration_proto_msgTypes,
	}.Build()
	File_live_administration_v1alpha1_githubintegration_proto = out.File
	file_live_administration_v1alpha1_githubintegration_proto_rawDesc = nil
	file_live_administration_v1alpha1_githubintegration_proto_goTypes = nil
	file_live_administration_v1alpha1_githubintegration_proto_depIdxs = nil
}
