// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.0
// source: live/administration/v1alpha1/gitlabintegration.proto

package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ReferenceType int32

const (
	ReferenceType_Branch ReferenceType = 0
	ReferenceType_Tag    ReferenceType = 1
	ReferenceType_MR     ReferenceType = 2
)

// Enum value maps for ReferenceType.
var (
	ReferenceType_name = map[int32]string{
		0: "Branch",
		1: "Tag",
		2: "MR",
	}
	ReferenceType_value = map[string]int32{
		"Branch": 0,
		"Tag":    1,
		"MR":     2,
	}
)

func (x ReferenceType) Enum() *ReferenceType {
	p := new(ReferenceType)
	*p = x
	return p
}

func (x ReferenceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReferenceType) Descriptor() protoreflect.EnumDescriptor {
	return file_live_administration_v1alpha1_gitlabintegration_proto_enumTypes[0].Descriptor()
}

func (ReferenceType) Type() protoreflect.EnumType {
	return &file_live_administration_v1alpha1_gitlabintegration_proto_enumTypes[0]
}

func (x ReferenceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReferenceType.Descriptor instead.
func (ReferenceType) EnumDescriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_gitlabintegration_proto_rawDescGZIP(), []int{0}
}

type GitlabIntegrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Host     string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *GitlabIntegrationResponse) Reset() {
	*x = GitlabIntegrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GitlabIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitlabIntegrationResponse) ProtoMessage() {}

func (x *GitlabIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitlabIntegrationResponse.ProtoReflect.Descriptor instead.
func (*GitlabIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_gitlabintegration_proto_rawDescGZIP(), []int{0}
}

func (x *GitlabIntegrationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GitlabIntegrationResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GitlabIntegrationResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type CreateGitlabIntegrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Host     string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Token    string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CreateGitlabIntegrationRequest) Reset() {
	*x = CreateGitlabIntegrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGitlabIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGitlabIntegrationRequest) ProtoMessage() {}

func (x *CreateGitlabIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGitlabIntegrationRequest.ProtoReflect.Descriptor instead.
func (*CreateGitlabIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_gitlabintegration_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGitlabIntegrationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateGitlabIntegrationRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *CreateGitlabIntegrationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateGitlabIntegrationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateGitlabIntegrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Integration *GitlabIntegrationResponse `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
}

func (x *CreateGitlabIntegrationResponse) Reset() {
	*x = CreateGitlabIntegrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGitlabIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGitlabIntegrationResponse) ProtoMessage() {}

func (x *CreateGitlabIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGitlabIntegrationResponse.ProtoReflect.Descriptor instead.
func (*CreateGitlabIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_gitlabintegration_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGitlabIntegrationResponse) GetIntegration() *GitlabIntegrationResponse {
	if x != nil {
		return x.Integration
	}
	return nil
}

type GetGitlabIntegrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetGitlabIntegrationRequest) Reset() {
	*x = GetGitlabIntegrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGitlabIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGitlabIntegrationRequest) ProtoMessage() {}

func (x *GetGitlabIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGitlabIntegrationRequest.ProtoReflect.Descriptor instead.
func (*GetGitlabIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_gitlabintegration_proto_rawDescGZIP(), []int{3}
}

func (x *GetGitlabIntegrationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetGitlabIntegrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Integration *GitlabIntegrationResponse `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
}

func (x *GetGitlabIntegrationResponse) Reset() {
	*x = GetGitlabIntegrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGitlabIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGitlabIntegrationResponse) ProtoMessage() {}

func (x *GetGitlabIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGitlabIntegrationResponse.ProtoReflect.Descriptor instead.
func (*GetGitlabIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_gitlabintegration_proto_rawDescGZIP(), []int{4}
}

func (x *GetGitlabIntegrationResponse) GetIntegration() *GitlabIntegrationResponse {
	if x != nil {
		return x.Integration
	}
	return nil
}

type DeleteGitlabIntegrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteGitlabIntegrationRequest) Reset() {
	*x = DeleteGitlabIntegrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGitlabIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGitlabIntegrationRequest) ProtoMessage() {}

func (x *DeleteGitlabIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGitlabIntegrationRequest.ProtoReflect.Descriptor instead.
func (*DeleteGitlabIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_gitlabintegration_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteGitlabIntegrationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteGitlabIntegrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Integration *GitlabIntegrationResponse `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
}

func (x *DeleteGitlabIntegrationResponse) Reset() {
	*x = DeleteGitlabIntegrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGitlabIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGitlabIntegrationResponse) ProtoMessage() {}

func (x *DeleteGitlabIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGitlabIntegrationResponse.ProtoReflect.Descriptor instead.
func (*DeleteGitlabIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_gitlabintegration_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteGitlabIntegrationResponse) GetIntegration() *GitlabIntegrationResponse {
	if x != nil {
		return x.Integration
	}
	return nil
}

type ListGitlabIntegrationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListGitlabIntegrationsRequest) Reset() {
	*x = ListGitlabIntegrationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGitlabIntegrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGitlabIntegrationsRequest) ProtoMessage() {}

func (x *ListGitlabIntegrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGitlabIntegrationsRequest.ProtoReflect.Descriptor instead.
func (*ListGitlabIntegrationsRequest) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_gitlabintegration_proto_rawDescGZIP(), []int{7}
}

type ListGitlabIntegrationsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Integrations []*GitlabIntegrationResponse `protobuf:"bytes,1,rep,name=integrations,proto3" json:"integrations,omitempty"`
}

func (x *ListGitlabIntegrationsResponse) Reset() {
	*x = ListGitlabIntegrationsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGitlabIntegrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGitlabIntegrationsResponse) ProtoMessage() {}

func (x *ListGitlabIntegrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGitlabIntegrationsResponse.ProtoReflect.Descriptor instead.
func (*ListGitlabIntegrationsResponse) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_gitlabintegration_proto_rawDescGZIP(), []int{8}
}

func (x *ListGitlabIntegrationsResponse) GetIntegrations() []*GitlabIntegrationResponse {
	if x != nil {
		return x.Integrations
	}
	return nil
}

type ListGitlabProjectsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,16,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ListGitlabProjectsRequest) Reset() {
	*x = ListGitlabProjectsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGitlabProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGitlabProjectsRequest) ProtoMessage() {}

func (x *ListGitlabProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGitlabProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListGitlabProjectsRequest) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_gitlabintegration_proto_rawDescGZIP(), []int{9}
}

func (x *ListGitlabProjectsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListGitlabProjectsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Integrations []*GitlabIntegration `protobuf:"bytes,1,rep,name=integrations,proto3" json:"integrations,omitempty"`
}

func (x *ListGitlabProjectsResponse) Reset() {
	*x = ListGitlabProjectsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGitlabProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGitlabProjectsResponse) ProtoMessage() {}

func (x *ListGitlabProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGitlabProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListGitlabProjectsResponse) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_gitlabintegration_proto_rawDescGZIP(), []int{10}
}

func (x *ListGitlabProjectsResponse) GetIntegrations() []*GitlabIntegration {
	if x != nil {
		return x.Integrations
	}
	return nil
}

type GitlabIntegration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owners []*GitlabProjectOwner `protobuf:"bytes,2,rep,name=owners,proto3" json:"owners,omitempty"`
}

func (x *GitlabIntegration) Reset() {
	*x = GitlabIntegration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GitlabIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitlabIntegration) ProtoMessage() {}

func (x *GitlabIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitlabIntegration.ProtoReflect.Descriptor instead.
func (*GitlabIntegration) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_gitlabintegration_proto_rawDescGZIP(), []int{11}
}

func (x *GitlabIntegration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GitlabIntegration) GetOwners() []*GitlabProjectOwner {
	if x != nil {
		return x.Owners
	}
	return nil
}

type GitlabProjectOwner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Projects []*GitlabProjectName `protobuf:"bytes,2,rep,name=projects,proto3" json:"projects,omitempty"`
}

func (x *GitlabProjectOwner) Reset() {
	*x = GitlabProjectOwner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GitlabProjectOwner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitlabProjectOwner) ProtoMessage() {}

func (x *GitlabProjectOwner) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitlabProjectOwner.ProtoReflect.Descriptor instead.
func (*GitlabProjectOwner) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_gitlabintegration_proto_rawDescGZIP(), []int{12}
}

func (x *GitlabProjectOwner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GitlabProjectOwner) GetProjects() []*GitlabProjectName {
	if x != nil {
		return x.Projects
	}
	return nil
}

type GitlabProjectName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GitlabProjectName) Reset() {
	*x = GitlabProjectName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GitlabProjectName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitlabProjectName) ProtoMessage() {}

func (x *GitlabProjectName) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitlabProjectName.ProtoReflect.Descriptor instead.
func (*GitlabProjectName) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_gitlabintegration_proto_rawDescGZIP(), []int{13}
}

func (x *GitlabProjectName) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GitlabProjectName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetGitlabProjectMetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IntegrationID string `protobuf:"bytes,1,opt,name=integrationID,proto3" json:"integrationID,omitempty"`
	ProjectID     string `protobuf:"bytes,2,opt,name=projectID,proto3" json:"projectID,omitempty"`
}

func (x *GetGitlabProjectMetadataRequest) Reset() {
	*x = GetGitlabProjectMetadataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGitlabProjectMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGitlabProjectMetadataRequest) ProtoMessage() {}

func (x *GetGitlabProjectMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGitlabProjectMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetGitlabProjectMetadataRequest) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_gitlabintegration_proto_rawDescGZIP(), []int{14}
}

func (x *GetGitlabProjectMetadataRequest) GetIntegrationID() string {
	if x != nil {
		return x.IntegrationID
	}
	return ""
}

func (x *GetGitlabProjectMetadataRequest) GetProjectID() string {
	if x != nil {
		return x.ProjectID
	}
	return ""
}

type GetGitlabProjectMetadataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta []*GitlabProjectReference `protobuf:"bytes,2,rep,name=meta,proto3" json:"meta,omitempty"`
}

func (x *GetGitlabProjectMetadataResponse) Reset() {
	*x = GetGitlabProjectMetadataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGitlabProjectMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGitlabProjectMetadataResponse) ProtoMessage() {}

func (x *GetGitlabProjectMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGitlabProjectMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetGitlabProjectMetadataResponse) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_gitlabintegration_proto_rawDescGZIP(), []int{15}
}

func (x *GetGitlabProjectMetadataResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetGitlabProjectMetadataResponse) GetMeta() []*GitlabProjectReference {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GitlabProjectReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sha  string        `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`
	Ref  string        `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Type ReferenceType `protobuf:"varint,3,opt,name=type,proto3,enum=ddev.administration.v1alpha1.ReferenceType" json:"type,omitempty"`
}

func (x *GitlabProjectReference) Reset() {
	*x = GitlabProjectReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GitlabProjectReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitlabProjectReference) ProtoMessage() {}

func (x *GitlabProjectReference) ProtoReflect() protoreflect.Message {
	mi := &file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitlabProjectReference.ProtoReflect.Descriptor instead.
func (*GitlabProjectReference) Descriptor() ([]byte, []int) {
	return file_live_administration_v1alpha1_gitlabintegration_proto_rawDescGZIP(), []int{16}
}

func (x *GitlabProjectReference) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *GitlabProjectReference) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *GitlabProjectReference) GetType() ReferenceType {
	if x != nil {
		return x.Type
	}
	return ReferenceType_Branch
}

var File_live_administration_v1alpha1_gitlabintegration_proto protoreflect.FileDescriptor

var file_live_administration_v1alpha1_gitlabintegration_proto_rawDesc = []byte{
	0x0a, 0x34, 0x6c, 0x69, 0x76, 0x65, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x67,
	0x69, 0x74, 0x6c, 0x61, 0x62, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x22, 0x5b, 0x0a, 0x19, 0x47, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x49, 0x6e,
	0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x76, 0x0a, 0x1e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x69, 0x74, 0x6c, 0x61,
	0x62, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x7c, 0x0a, 0x1f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x47, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0b,
	0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x37, 0x2e, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2e, 0x47, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2d, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x47, 0x69,
	0x74, 0x6c, 0x61, 0x62, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x79, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x47, 0x69, 0x74,
	0x6c, 0x61, 0x62, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x64, 0x64,
	0x65, 0x76, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x47, 0x69, 0x74, 0x6c, 0x61,
	0x62, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x30, 0x0a, 0x1e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x69, 0x74, 0x6c, 0x61,
	0x62, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x7c, 0x0a, 0x1f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x69, 0x74,
	0x6c, 0x61, 0x62, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x64, 0x64,
	0x65, 0x76, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x47, 0x69, 0x74, 0x6c, 0x61,
	0x62, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x1f, 0x0a, 0x1d, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x49,
	0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x7d, 0x0a, 0x1e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x69, 0x74, 0x6c, 0x61, 0x62,
	0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x64, 0x64, 0x65,
	0x76, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x47, 0x69, 0x74, 0x6c, 0x61, 0x62,
	0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x2b, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x71,
	0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x0c,
	0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x47, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x6d, 0x0a, 0x11, 0x47, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x49, 0x6e, 0x74, 0x65, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x48, 0x0a, 0x06, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x47, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x73,
	0x22, 0x75, 0x0a, 0x12, 0x47, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x4b, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x64,
	0x64, 0x65, 0x76, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x47, 0x69, 0x74, 0x6c,
	0x61, 0x62, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x08, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x37, 0x0a, 0x11, 0x47, 0x69, 0x74, 0x6c, 0x61,
	0x62, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x65, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x47, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x74, 0x65,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x22, 0x7c, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x47, 0x69,
	0x74, 0x6c, 0x61, 0x62, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x48, 0x0a, 0x04, 0x6d,
	0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x64, 0x64, 0x65, 0x76,
	0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x47, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52,
	0x04, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x7d, 0x0a, 0x16, 0x47, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x68, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x68,
	0x61, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x72, 0x65, 0x66, 0x12, 0x3f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x2b, 0x2e, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x2a, 0x2c, 0x0a, 0x0d, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x4d, 0x52,
	0x10, 0x02, 0x42, 0x7c, 0x0a, 0x25, 0x63, 0x6f, 0x6d, 0x2e, 0x64, 0x64, 0x65, 0x76, 0x2e, 0x6c,
	0x69, 0x76, 0x65, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x42, 0x16, 0x47, 0x69, 0x74,
	0x6c, 0x61, 0x62, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x64, 0x72, 0x75, 0x64, 0x2f, 0x64, 0x64, 0x65, 0x76, 0x2d, 0x61, 0x70, 0x69, 0x73,
	0x2d, 0x67, 0x6f, 0x2f, 0x6c, 0x69, 0x76, 0x65, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_live_administration_v1alpha1_gitlabintegration_proto_rawDescOnce sync.Once
	file_live_administration_v1alpha1_gitlabintegration_proto_rawDescData = file_live_administration_v1alpha1_gitlabintegration_proto_rawDesc
)

func file_live_administration_v1alpha1_gitlabintegration_proto_rawDescGZIP() []byte {
	file_live_administration_v1alpha1_gitlabintegration_proto_rawDescOnce.Do(func() {
		file_live_administration_v1alpha1_gitlabintegration_proto_rawDescData = protoimpl.X.CompressGZIP(file_live_administration_v1alpha1_gitlabintegration_proto_rawDescData)
	})
	return file_live_administration_v1alpha1_gitlabintegration_proto_rawDescData
}

var file_live_administration_v1alpha1_gitlabintegration_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_live_administration_v1alpha1_gitlabintegration_proto_goTypes = []interface{}{
	(ReferenceType)(0),                       // 0: ddev.administration.v1alpha1.ReferenceType
	(*GitlabIntegrationResponse)(nil),        // 1: ddev.administration.v1alpha1.GitlabIntegrationResponse
	(*CreateGitlabIntegrationRequest)(nil),   // 2: ddev.administration.v1alpha1.CreateGitlabIntegrationRequest
	(*CreateGitlabIntegrationResponse)(nil),  // 3: ddev.administration.v1alpha1.CreateGitlabIntegrationResponse
	(*GetGitlabIntegrationRequest)(nil),      // 4: ddev.administration.v1alpha1.GetGitlabIntegrationRequest
	(*GetGitlabIntegrationResponse)(nil),     // 5: ddev.administration.v1alpha1.GetGitlabIntegrationResponse
	(*DeleteGitlabIntegrationRequest)(nil),   // 6: ddev.administration.v1alpha1.DeleteGitlabIntegrationRequest
	(*DeleteGitlabIntegrationResponse)(nil),  // 7: ddev.administration.v1alpha1.DeleteGitlabIntegrationResponse
	(*ListGitlabIntegrationsRequest)(nil),    // 8: ddev.administration.v1alpha1.ListGitlabIntegrationsRequest
	(*ListGitlabIntegrationsResponse)(nil),   // 9: ddev.administration.v1alpha1.ListGitlabIntegrationsResponse
	(*ListGitlabProjectsRequest)(nil),        // 10: ddev.administration.v1alpha1.ListGitlabProjectsRequest
	(*ListGitlabProjectsResponse)(nil),       // 11: ddev.administration.v1alpha1.ListGitlabProjectsResponse
	(*GitlabIntegration)(nil),                // 12: ddev.administration.v1alpha1.GitlabIntegration
	(*GitlabProjectOwner)(nil),               // 13: ddev.administration.v1alpha1.GitlabProjectOwner
	(*GitlabProjectName)(nil),                // 14: ddev.administration.v1alpha1.GitlabProjectName
	(*GetGitlabProjectMetadataRequest)(nil),  // 15: ddev.administration.v1alpha1.GetGitlabProjectMetadataRequest
	(*GetGitlabProjectMetadataResponse)(nil), // 16: ddev.administration.v1alpha1.GetGitlabProjectMetadataResponse
	(*GitlabProjectReference)(nil),           // 17: ddev.administration.v1alpha1.GitlabProjectReference
}
var file_live_administration_v1alpha1_gitlabintegration_proto_depIdxs = []int32{
	1,  // 0: ddev.administration.v1alpha1.CreateGitlabIntegrationResponse.integration:type_name -> ddev.administration.v1alpha1.GitlabIntegrationResponse
	1,  // 1: ddev.administration.v1alpha1.GetGitlabIntegrationResponse.integration:type_name -> ddev.administration.v1alpha1.GitlabIntegrationResponse
	1,  // 2: ddev.administration.v1alpha1.DeleteGitlabIntegrationResponse.integration:type_name -> ddev.administration.v1alpha1.GitlabIntegrationResponse
	1,  // 3: ddev.administration.v1alpha1.ListGitlabIntegrationsResponse.integrations:type_name -> ddev.administration.v1alpha1.GitlabIntegrationResponse
	12, // 4: ddev.administration.v1alpha1.ListGitlabProjectsResponse.integrations:type_name -> ddev.administration.v1alpha1.GitlabIntegration
	13, // 5: ddev.administration.v1alpha1.GitlabIntegration.owners:type_name -> ddev.administration.v1alpha1.GitlabProjectOwner
	14, // 6: ddev.administration.v1alpha1.GitlabProjectOwner.projects:type_name -> ddev.administration.v1alpha1.GitlabProjectName
	17, // 7: ddev.administration.v1alpha1.GetGitlabProjectMetadataResponse.meta:type_name -> ddev.administration.v1alpha1.GitlabProjectReference
	0,  // 8: ddev.administration.v1alpha1.GitlabProjectReference.type:type_name -> ddev.administration.v1alpha1.ReferenceType
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_live_administration_v1alpha1_gitlabintegration_proto_init() }
func file_live_administration_v1alpha1_gitlabintegration_proto_init() {
	if File_live_administration_v1alpha1_gitlabintegration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GitlabIntegrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGitlabIntegrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGitlabIntegrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGitlabIntegrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGitlabIntegrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGitlabIntegrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGitlabIntegrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGitlabIntegrationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGitlabIntegrationsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGitlabProjectsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGitlabProjectsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GitlabIntegration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GitlabProjectOwner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GitlabProjectName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGitlabProjectMetadataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGitlabProjectMetadataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GitlabProjectReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_live_administration_v1alpha1_gitlabintegration_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_live_administration_v1alpha1_gitlabintegration_proto_goTypes,
		DependencyIndexes: file_live_administration_v1alpha1_gitlabintegration_proto_depIdxs,
		EnumInfos:         file_live_administration_v1alpha1_gitlabintegration_proto_enumTypes,
		MessageInfos:      file_live_administration_v1alpha1_gitlabintegration_proto_msgTypes,
	}.Build()
	File_live_administration_v1alpha1_gitlabintegration_proto = out.File
	file_live_administration_v1alpha1_gitlabintegration_proto_rawDesc = nil
	file_live_administration_v1alpha1_gitlabintegration_proto_goTypes = nil
	file_live_administration_v1alpha1_gitlabintegration_proto_depIdxs = nil
}
